[site]

name = "Karaty Offical"

title-suffix = " | Karaty Site"

dark-mode = true

[repository]

service = "GitHub"

name = "mrxiaozhuox/karaty"

[data-source]

mode = "custom-url"

data = { url = "/source/", index-file = "index.json" }

[[routing]]
path = "/"
file = "home.md"

[routing.template]

using = "center"

[routing.template.style]

ul = "list-none"

[[routing]]
path = "/author"
file = "author.md"

[routing.template]

using = "center"

[routing.template.style]

img = "rounded-full"

[[routing]]
path = "/dependencies"
file = "dependencies.json"

[[routing]]
path = "/blog"
preset = "post-list"

[[routing]]
path = "/blog/:path"
preset = "post-content"

[navigation]

links = [
    { text = "Home", page = "/" },
    { text = "My Github", link = "https://github.com/mrxiaozhuox/" },
    { feature = "mode-switch" },
]

[footer]

# enable = false

content = [
    [
        { text = "Home", page = "/" },
        { text = "Dependencies", page = "/dependencies" },
        { text = "Blog", page = "/blog" },
        { text = "Author", page = "/author" },
    ],
    [
        { icon = "brand:github", link = "https://github.com/mrxiaozhuox/karaty" },
        { icon = "brand:zhihu", link = "https://www.zhihu.com/people/mrxiao-zhuo-x" },
        { icon = "brand:instagram", link = "https://www.instagram.com/mrxiaozhuox/" },
    ]
]