[site]

name = "Karaty Offical"

title-suffix = " | Karaty Site"

dark-mode = true

[repository]

service = "GitHub"

name = "mrxiaozhuox/karaty"

[data-source]
mode = "embedded-repository"

data = "data"

[data-source.local]
mode = "custom-url"

data = { url = "/source/", index-file = "_index.json" }

[[routing]]
path = "/"
file = "home.md"

[routing.template]

using = "center"

[[routing]]
path = "/author"
file = "author.md"

[routing.template]

using = "center"

[routing.template.style]

img = "rounded-full"

[[routing]]
path = "/dependencies"
file = "dependencies.json"

[[routing]]
path = "/blog"
preset = "post-list"
setting = { group = "blog" }

[[routing]]
path = "/blog/:path"
preset = "post-content"
setting = { group = "blog", file = ":path" }

[[routing]]
path = "/docs"
redirect = "/docs/summary"

[[routing]]
path = "/docs/:path"
preset = "post-content"
setting = { group = "docs", file = ":path" }

[routing.template]
using = "docs"

[navigation]

links = [
    { text = "Home", page = "/" },
    { feature = "mode-switch" },
]

[footer]

# enable = false

content = [
    [
        { text = "Home", page = "/" },
        { text = "Dependencies", page = "/dependencies" },
        { text = "Blog", page = "/blog" },
        { text = "Docs", page = "/docs" },
        { text = "Author", page = "/author" },
    ],
    [
        { icon = "brand:github", link = "https://github.com/mrxiaozhuox/karaty" },
        { icon = "brand:zhihu", link = "https://www.zhihu.com/people/mrxiao-zhuo-x" },
        { icon = "brand:instagram", link = "https://www.instagram.com/mrxiaozhuox/" },
    ]
]