[site]

name = "Karaty Offical"

title-suffix = " | Karaty Site"

dark-mode = true

[repository]

service = "GitHub"

name = "mrxiaozhuox/karaty"

[data-source]
mode = "embedded-repository"

data = "data"

[data-source.local]
mode = "custom-url"

data = { url = "/source/", index-file = "_index.json" }

[routing]

remote = "/routing.toml"

[navigation]

content = [
    { text = "Home", page = "/" },
    { text = "Blog", page = "/blog" },
    { text = "Docs", page = "/docs" },
    { text = "Roadmap", page = "/blog/roadmap" },
    { text = "About", list = [
        { text = "Dependencies", page = "/dependencies" },
        { text = "Author", page = "/author" },
    ] },
    { feature = "mode-switch" },
]

[footer]

content = [
    [
        { icon = "brand.github", link = "https://github.com/mrxiaozhuox/karaty" },
        { icon = "brand.zhihu", link = "https://www.zhihu.com/people/mrxiao-zhuo-x" },
        { icon = "brand.instagram", link = "https://www.instagram.com/mrxiaozhuox/" },
    ],
    [{ text = "Powered by Karaty" }],
]