[site]

name = "Karaty Offical"

title-suffix = " | Karaty Site"

dark-mode = true

[deploy.repository]

service = "GitHub"

name = "mrxiaozhuox/karaty"

[deploy.data-source]

# mode = "independent-repository"

# data = { service = "GitHub", name = "mrxiaozhuox/blog.mrxzx.info", branch = "master" }

mode = "sub-path"

data = "template"