[site]

name = "Karaty Offical"

title-suffix = " | Karaty Site"

dark-mode = true

homepage = "home.md"

[repository]

service = "GitHub"

name = "mrxiaozhuox/karaty"

[data-source]

# mode = "independent-repository"

# data = { service = "GitHub", name = "mrxiaozhuox/blog.mrxzx.info", branch = "master" }

mode = "sub-path"

data = "template"

[navigation]

links = [
    { text = "Home", page = "home.md" },
    { text = "My Github", link = "https://github.com/mrxiaozhuox/" },
    { feature = "mode-switch" },
]

[footer]

# enable = false

content = [
    [
        { text = "Home", page = "home.md" },
        { text = "Projects", page = "projects.json" },
        { text = "Blog", page = "$blog" },
        { text = "About", page = "about.md" },
    ],
    [
        { feature = "mode-switch" },
        { icon = "brand:github", link = "https://github.com/mrxiaozhuox/karaty" },
        { icon = "brand:zhihu", link = "https://www.zhihu.com/people/mrxiao-zhuo-x" },
    ],
    [
        { text = "@mrxiaozhuox - 2023" }
    ]
]