name: release-package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown
          override: true
      - name: Install CLI
        shell: bash
        run: cargo install --git https://github.com/Dioxuslabs/dioxus dioxus-cli --tag=v0.4.3
      - name: Build Karaty
        shell: bash
        run: cd karaty && dx build --release
      - name: Clean Data
        shell: bash
        run: cd karaty && cd dist && rm CNAME && rm -rf data
      - uses: montudor/action-zip@v1
        run: zip -qq -r karaty.zip dist
        working-directory: ./karaty
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "karaty/dist/assets/dioxus/karaty_bg.wasm,karaty.zip"
          generateReleaseNotes: true
